/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Church.gltf --transform 
Files: Church.gltf [1.76MB] > Church-transformed.glb [724.43KB] (59%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Church(props) {
  const { nodes, materials } = useGLTF('/models/Church-transformed.glb')
  return (
    <group scale={0.9} {...props} dispose={null}>
      <group position={[-14.485, 7.55, -23.621]} rotation={[Math.PI / 2, 0, 0]} scale={[0.275, 0.64, 0.181]}>
        <mesh geometry={nodes.Mesh091.geometry} material={materials['Gold.002']} />
        <mesh geometry={nodes.Mesh091_1.geometry} material={materials['Ceramic.002']} />
      </group>
      <mesh geometry={nodes.Object.geometry} material={materials['Brick.002']} position={[-14.485, 7.57, -48.362]} rotation={[Math.PI / 2, 0, 0]} scale={[0.275, 0.64, 0.181]} />
      <mesh geometry={nodes.Object016.geometry} material={materials['Roof.004']} position={[-14.485, 7.55, -48.372]} rotation={[Math.PI / 2, 0, 0]} scale={[0.275, 0.64, 0.181]} />
      <mesh geometry={nodes.Object018.geometry} material={materials['Wood.002']} position={[-14.485, 7.55, -48.372]} rotation={[Math.PI / 2, 0, 0]} scale={[0.275, 0.64, 0.181]} />
      <mesh geometry={nodes.Object020.geometry} material={materials['23 - Default.002']} position={[-14.485, 7.55, -48.372]} rotation={[Math.PI / 2, 0, 0]} scale={[0.275, 0.64, 0.181]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Grass.002']} position={[-6.153, 0, -62.73]} scale={0.097} />
      <mesh geometry={nodes.Object027.geometry} material={materials['Material #474.002']} position={[-14.485, 7.55, -48.372]} rotation={[Math.PI / 2, 0, 0]} scale={[0.275, 0.64, 0.181]} />
      <mesh geometry={nodes.Box001.geometry} material={materials['22 - Default.002']} position={[-3.516, 5.902, -5.614]} rotation={[1.567, 0, 0]} scale={[0.146, 0.082, 0.146]} />
      <mesh geometry={nodes.Object055.geometry} material={materials['Material #539.002']} position={[-14.485, 7.55, -48.372]} rotation={[Math.PI / 2, 0, 0]} scale={[0.275, 0.64, 0.181]} />
      <mesh geometry={nodes.Object056.geometry} material={materials['Material #551.002']} position={[-14.485, 7.55, -48.372]} rotation={[Math.PI / 2, 0, 0]} scale={[0.275, 0.64, 0.181]} />
      <instancedMesh args={[nodes.Mesh090.geometry, materials['Gold.002'], 8]} instanceMatrix={nodes.Mesh090.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh111.geometry, materials['Brick.002'], 10]} instanceMatrix={nodes.Mesh111.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh123.geometry, materials['23 - Default.002'], 10]} instanceMatrix={nodes.Mesh123.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/Church-transformed.glb')
