/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 JustinHead.gltf --transform 
Files: JustinHead.gltf [6.85MB] > JustinHead-transformed.glb [314.84KB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/JustinHead-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Group1.geometry} material={materials['default']} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/JustinHead-transformed.glb')
