// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.13 scene.gltf --transform 
// Files: scene.gltf [9.15MB] > scene-transformed.glb [1.66MB] (82%)
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function PortfolioEnvironment(props) {
//   const { nodes, materials } = useGLTF('/models/portfolio-environment-transformed.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group position={[4.617, 0, -0.001]} rotation={[-Math.PI / 2, 0, 0.034]} scale={-0.001}>
//         <mesh geometry={nodes.Mesh.geometry} material={materials.Face} />
//         <mesh geometry={nodes.Mesh_1.geometry} material={materials.PaletteMaterial001} />
//         <mesh geometry={nodes.Mesh_2.geometry} material={materials.PaletteMaterial002} />
//       </group>
//       <mesh geometry={nodes.pWater.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} scale={[18.195, 23.923, 12.363]} />
//       <mesh geometry={nodes.billboard_3.geometry} material={materials.PokiTheDog} position={[0, -0.005, 0]} rotation={[Math.PI / 2, 0, -0.203]} scale={0.011} />
//       <mesh geometry={nodes.pPlane3.geometry} material={materials.Poki} position={[3.713, 0.091, -1.159]} rotation={[0.246, -1.374, -2.947]} scale={[0.338, 0.231, 0.231]} />
//       <group position={[-0.895, -0.088, 0.088]} rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
//         <mesh geometry={nodes.Mesh009.geometry} material={materials.WoodenSign} />
//         <mesh geometry={nodes.Mesh009_1.geometry} material={materials.AppsAndWebsitesSign} />
//       </group>
//       <mesh geometry={nodes.billboard_4.geometry} material={materials.JustinOldPortfolioBanner} position={[0, -0.005, 0]} rotation={[Math.PI / 2, 0, -0.405]} scale={0.011} />
//       <mesh geometry={nodes.billboard_5.geometry} material={materials.OttawaRecSports} position={[0, -0.005, 0]} rotation={[Math.PI / 2, 0, -0.608]} scale={0.011} />
//       <mesh geometry={nodes.billboard_6.geometry} material={materials.DailyWorshipper} position={[0, -0.005, 0]} rotation={[Math.PI / 2, 0, -0.811]} scale={0.011} />
//       <mesh geometry={nodes.JesusHill.geometry} material={materials.dirt} position={[0, -0.552, 0.035]} rotation={[-Math.PI, 1.254, Math.PI]} scale={0} />
//       <mesh geometry={nodes.pCube3.geometry} material={materials.Wood} position={[0.135, 1.028, -0.03]} rotation={[Math.PI / 2, 0, -1.888]} scale={[0.011, 0.024, 0.011]} />
//       <instancedMesh args={[nodes.Mesh013.geometry, materials.PaletteMaterial003, 23]} instanceMatrix={nodes.Mesh013.instanceMatrix} />
//       <instancedMesh args={[nodes.Mesh013_1.geometry, materials.PokiTheDog, 23]} instanceMatrix={nodes.Mesh013_1.instanceMatrix} />
//     </group>
//   )
// }

// useGLTF.preload('/models/portfolio-environment-transformed.glb')
